CREATE TABLE EMPLOYEES_AUD (
  EVENT_ID SERIAL NOT NULL PRIMARY KEY UNIQUE,
  EVENT_DATE TIMESTAMP NOT NULL,
  EVENT_TYPE VARCHAR(10) DEFAULT NULL,
  OLD_ID INTEGER,
  NEW_ID INTEGER,
  OLD_FORENAME VARCHAR(50),
  NEW_FORENAME VARCHAR(50),
  OLD_SURNAME VARCHAR(50),
  NEW_SURNAME VARCHAR(50)
);