DROP TRIGGER employee_insert ON EMPLOYEES;
DROP FUNCTION log_employee_after_insert();

CREATE OR REPLACE FUNCTION log_employee_after_insert()
  RETURNS TRIGGER AS
$BODY$
BEGIN
  INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, NEW_ID, NEW_FORENAME, NEW_SURNAME)
  VALUES (CURRENT_TIMESTAMP, 'INSERT', NEW.ID, NEW.FORENAME, NEW.SURNAME);
  RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER employee_insert
  AFTER INSERT
  ON EMPLOYEES
  FOR EACH ROW
EXECUTE PROCEDURE log_employee_after_insert();