CREATE OR REPLACE FUNCTION log_employee_after_update()
  RETURNS TRIGGER AS
$BODY$
BEGIN
  INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, OLD_ID, NEW_ID, OLD_FORENAME, NEW_FORENAME, OLD_SURNAME, NEW_SURNAME)
  VALUES (CURRENT_TIMESTAMP, 'UPDATE', OLD.ID, NEW.ID, OLD.FORENAME, NEW.FORENAME, OLD.SURNAME, NEW.SURNAME);
  RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;