CREATE OR REPLACE FUNCTION log_employee_after_delete()
  RETURNS TRIGGER AS
$BODY$
BEGIN
  INSERT INTO EMPLOYEES_AUD (EVENT_DATE, EVENT_TYPE, OLD_ID, OLD_FORENAME, OLD_SURNAME)
  VALUES (CURRENT_TIMESTAMP, 'DELETE', OLD.ID, OLD.FORENAME, OLD.SURNAME);
  RETURN NEW;
END;
$BODY$
LANGUAGE plpgsql;